import { ReactNode } from 'react';
import Head from 'next/head';
import Footer from '@components/global/Footer';
import Header from '@components/global/Header';

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Food Ordering App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="md:flex md:flex-col">
        <Header />
        <main className="md:mb-10 xl:mx-auto">{children}</main>
        <Footer />
      </div>
    </>
  );
}
